### ISSUE TITLE
TypeError: setup(): incompatible function arguments

### ISSUE THREAD

**Issue by willwheelera** [hungpham2017/pyWannier90#4]
When trying to run the h2.py example, I get the following error

    Traceback (most recent call last):
      File "h2.py", line 47, in <module>
        w90.setup()
      File "/projects/wagner/wawheel2/code/pyscf/pyscf/pbc/tools/pywannier90.py", line 540, in setup
        self.atom_atomic_loc, atoms_cart_loc, self.gamma_only, self.spinors) 
    TypeError: setup(): incompatible function arguments. The following argument types are supported:
        1. (arg0: numpy.ndarray[int32], arg1: int, arg2: numpy.ndarray[float64], arg3: numpy.ndarray[float64], arg4: numpy.ndarray[float64], arg5: int, arg6: int, arg7: numpy.ndarray[int32], arg8: numpy.ndarray[float64], arg9: int, arg10: int) -> List[numpy.ndarray[float64]]

    Invoked with: 'wannier90', [2, 2, 2], 8, array([3., 0., 0., 0., 3., 0., 0., 0., 3.]), array([2.0943951, 0.       , 0.       , 0.       , 2.0943951, 0.       , 
           0.       , 0.       , 2.0943951]), array([0. , 0. , 0. , 0. , 0. , 0.5, 0. , 0.5, 0. , 0. , 0.5, 0.5, 0.5,  
           0. , 0. , 0.5, 0. , 0.5, 0.5, 0.5, 0. , 0.5, 0.5, 0.5]), 4, 2, [1, 1], array([1.5, 1.5, 1. , 1.5, 1.5, 2. ]), 0, 0

None of the argument types seem wrong, so I'm confused about what the problem is.

**Comment by hungpham2017** [comment]
Hello,

The problem was because of the consistency between libwannier90 and pywannier90 (in PySCF)
So I have updated the libwannier90 to work with wannier90-3.0.0 and 3.1.0
BUT I have not pushed the new pywannier90.py for PySCF yet. I am still working on more functions and some minor bug fix before submit a pull request for PySCF. I hope to do PR sometimes next week.

In the meantime, it is very easy to modify your own local version of pywannier90.py in PySCF to work with the current libwannier90. 
You can simply **delete the seed__name** (together with the comma next to it) when calling the setup() and run() function in pywannier90.py file (should be located in pbc/tools/pywannier90.py.

![image](https://user-images.githubusercontent.com/30437431/82519030-4fc9c400-9ae6-11ea-96cc-850512865278.png)

Similarly for the run() function:

![image](https://user-images.githubusercontent.com/30437431/82519079-6f60ec80-9ae6-11ea-93ee-eb8922b0b061.png)

Sorry for this inconvenience
Please let me know if it does work for you. I will let you know when the new version is merged to at least the dev branch of PySCF.

**Comment by willwheelera** [comment]
Thanks for the quick response and for the fix! I removed the seed__name argument, and also had to remove the argument self.num_bands_tot in run(), and then the h2 example worked.
